name: CI
on:
  pull_request:
    branches:
      - 'master'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: ESLint
        run: npm run eslint
      - name: TypeScript
        run: npm run tsc
